export const metadata = {
  title: 'Next上課範例',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
          {/* <h1>logo-header選單列</h1> */}
        {children}
          {/* <h1>Footer</h1> */}
      </body>
    </html>
  )
}
